#File Updated for key : endMeterReading
#Fri Mar 01 18:38:50 IST 2024

appPackage=com.bitbar.testdroid
//reportName=Automation Report
reportPathAppendDate=Yes
//resourcePath=src/main/resources
edgeDriverPath=src/main/resources/msedgedriver.exe
sheetname=TestData
automationName=UIAutomator2
platformName=Android
remoteAddress=http\://127.0.0.1\:portNumber/
//remoteAddress=http://127.0.0.1:portNumber
app=C\:\\Bosch\\WebMobileAPIAutomation\\App\\bitbar-sample-app.apk
reportPath=Reports
author=Tauseef
//count=0
appActivity=com.bitbar.testdroid.BitbarSampleApplicationActivity
//webUrlConfirmation=https://www.eye2serve.com:9001/sap/bc/ui5_ui5/ui2/ushell/shells/abap/FioriLaunchpad.html#Shell-home
category=Regression Mobile
chromeDriverPath=src/main/resources/webresources/chromedriver.exe
browser=chrome
environment=QA